name: CI

on:
  pull_request:
    branches:
      - master

# Remove this if you don't want older CI runs to be canceled if newer ones are pushed
concurrency:
  group:  ${{ github.ref }} 
  cancel-in-progress: true

jobs:
  elixir:
    uses: primait/shared-github-actions/.github/workflows/elixir-ci.yml@elixir-ci-v2
    with:
      runs-on: k8s-medium
      elixir-version: "1.14.5-otp-25"
      otp-version: "25.3"

  # This can be used to handle CI requirements "in-repo" by setting the `needs`
  alls-green:
    if: always()
    needs:
      - elixir
    runs-on: [self-hosted, k8s-small]
    container:
      image: public.ecr.aws/prima/python:3.9.10-3
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs:  ${{ toJSON(needs) }} 
          
